apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dotmakeup-kilo
spec:
  selector:
    matchLabels:
      app: dotmakeup
      network: instagram
  serviceName: "dotmakeup"
  replicas: 1 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: dotmakeup 
        network: instagram
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: network
                    operator: In
                    values:
                      - instagram
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 30
      containers:
        - name: dotmakeup
          image: cloutier/bird.makeup:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: web
          resources:
            requests:
              memory: "900Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
          envFrom:
            - secretRef:
                name: grafana
          env:
            - name: Instance__domain
              value: "kilogram.makeup"
            - name: Instance__Name
              value: "kilogram.makeup"
            - name: Instance__TwitterRequestDelay
              value: "1000000"
            - name: Instance__SocialNetworkRequestJitter
              value: "19000"
            - name: Instance__ParallelTwitterRequests
              value: "1"
            - name: Instance__SidecarURL
              value: "http://100.100.41.58:5000"
            - name: Instance__CrawlingSidecarURL
              value: "http://localhost:5000"
            - name: "Instance__IpfsApi"
              value: "http://100.102.85.102:5001"
            - name: "Instance__IpfsGateway"
              value: "ipfs.kilogram.makeup"
            - name: Instance__SocialNetwork
              value: "Instagram"
            - name: Instance__ParallelFediversePosts
              value: "10"
            - name: Instance__UserCacheCapacity
              value: "5000"
            - name: Instance__TweetCacheCapacity
              value: "5000"
            - name: Instance__MultiplyNByOrdinal
              value: "true"
            - name: Instance__n_start
              value: "0"
            - name: Instance__n_end
              value: "20"
            - name: Instance__m
              value: "79"
            - name: db__type
              value: "postgres"
            - name: db__host
              valueFrom:
                secretKeyRef:
                  name: dotmakeup-db
                  key: host
            - name: db__port
              value: "20184"
            - name: db__name
              valueFrom:
                secretKeyRef:
                  name: dotmakeup-db
                  key: name
            - name: db__user
              valueFrom:
                secretKeyRef:
                  name: dotmakeup-db
                  key: user
            - name: db__password
              valueFrom:
                secretKeyRef:
                  name: dotmakeup-db
                  key: password
          livenessProbe:
            httpGet:
              path: /About
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:latest
          securityContext:
            privileged: true
          imagePullPolicy: Always
          env:
            - name: "TS_KUBE_SECRET"
              value: ""
            - name: "TS_USERSPACE"
              value: "false"
            - name: "TS_STATE_DIR"
              value: "/var/lib/tailscale"
            - name: "TS_AUTHKEY"
              valueFrom:
                secretKeyRef:
                  name: tailscale
                  key: ts_authkey
          volumeMounts:
            - name: ts
              mountPath: /var/lib/tailscale
        - name: dotmakeup-social-sidecar
          image: cloutier/dotmakeup-social-sidecar:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: sidecar
          env:
            - name: "HTTP_PROXY"
              valueFrom:
                secretKeyRef:
                  name: http-proxy
                  key: proxy
                  optional: true
            - name: "HTTPS_PROXY"
              valueFrom:
                secretKeyRef:
                  name: http-proxy
                  key: proxy
                  optional: true
  volumeClaimTemplates:
    - metadata:
        name: ts
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "csi-cinder-classic"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dotmakeup-kilo
spec:
  type: ClusterIP
  selector:
    app: dotmakeup
    network: instagram
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080